### PR TITLE
removing assistant job ad

### PR DESCRIPTION
**Pull request by alexatsatoshi**

### CODE REVIEW

**Comment by Levino** [comment]
Please delete stale branches!

**Comment by Levino** [comment]
@rashagen

**Comment by meinharrd** [comment]
@rashagen https://github.com/satoshipay/satoshipay.github.io/blob/master/_pages/jobs/teamassistenz.md needs to go as well

**Comment by Levino** [comment]
@meinharrd : 

1. @alexatsatoshi created this, he is the owner.
2. See https://github.com/satoshipay/satoshipay.github.io/pull/64

**Pull request merged**
