### PR TITLE
Jobs team fixes

### PR DESCRIPTION
**Pull request by rashagen**
* Add Florian
* Add We're Hiring button (responsively positioned)
* Add "freelancers" to About Us team

### CODE REVIEW

**Comment by Levino** [comment]
selection_021

Broken in responsive view.

**Comment by Levino** [comment]
selection_022
There seems to be a breakpoint where the font for the 'LOGIN' and 'SIGN UP' buttons gets smaller. The Jobs button stays large

**Comment by Levino** [comment]
@rashagen I leave it to you to set up issues for this and fix them later. In order to move forward I merged so we have the button up there.

**Comment by rashagen** [comment]
@Levino where did you see the broken responsive view? Which viewport size/device?

**Comment by rashagen** [comment]
selection_022

Feature, not a bug

**Comment by Levino** [comment]
selection_024

**Pull request merged**
